---
- name: add user
  hosts: install_hosts
  become: true

  tasks:
    - name: Add user
      ansible.builtin.user:
        name: "{{ user_name }}"
        password: "{{ user_password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: users, serverusers, servermaintainers
        update_password: on_create
        state: present